### ISSUE TITLE
web app build fails

### ISSUE THREAD

**Issue by sangecz** [MarcinMoskala/KotlinAcademyApp#3]
building root gradle file succeeds but building web app fails.

I run: `npm install; npm run serve` and it complains about missing files: (common-client-js.js, web.js required from web/src/main/js/index.js). Also I could not find any actual building of common-client-js file (quick find in path..).

how can I solve that, are there any instructions how to use this project?

**Comment by MarcinMoskala** [comment]
Sorry for that. I introduced new task to Android and I added expected declaration in `common-client` and I forgot to make actual declaration in `common-client-js`. I am adding the instruction how to start all the clients. 

I am always moving to web and running `gradle build` and then `npm run serve` (although `gradle :web:run` should work too). Sometimes I need to make `npm run serve` two times because there are errors during first run (sorry for that. I will fix it whenever I will have some time)
