### ISSUE TITLE
can't update cards in waffle

### ISSUE THREAD

**Issue by letroll** [MarcinMoskala/KotlinAcademyApp#34]
I can't update cards in waffle (logged with my github account) because "only collaborator can" say a notification when I try...

**Comment by MarcinMoskala** [comment]
This is expected behavior because only collaborators can update them. You can comment every issue and say that you work on it or that there are some problems. You can also create issues yourself (like you just did). We are happy to welcome you to this project if you are willing to contribute. For a longer discussion, you can write to me at marcinmoskala@gmail.com or via Kotlin Slack.
